### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by TeukuMaulana** [fatah4561/skpi#2]
Setelah saya cek, Folder Vendor dan file di dalam Vendor nggak ada mas fatah, dan juga DB nya..
boleh di share mas..?
maaf kalau saya salah dalam memprediksi..belum pernah pegang laravel soalnya 

Terimakasih

**Comment by fatah4561** [comment]
Untuk vendor isinya bisa di cmd / powershell "composer install" untuk DB bisa setelah setting .env DB nya nanti tinggal "php artisan migrate" sama untuk data db nya bisa di command "php artisan db:seed"

**Comment by TeukuMaulana** [comment]
Tadi sudah coba bang seperti itu pakai "php artisan migrate,, tapi gagal
bang,, besok saya coba lagi.. 🙏

**Comment by fatah4561** [comment]
gagal nya gimana bang? saya juga udah lama ga buka project ini hmm kalau ga salah belum beres juga sih 😂, hmm nanti kalau sempet diberesih sih kayanya
